version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
